jQuery(document).ready(function(){
    $('.slider__auto .owl-carousel').owlCarousel({
      loop:true,
      margin:10,
      smartSpeed:1000,
      autoplay:true,
      autoplayTimeout:3000,
      autoplayHoverPause:true,
      responsiveClass:true,
      nav:true,
      responsive:{
          0:{
              items:2
          },
          600:{
              items:3
          },
          1000:{
              items:5
          }
      }
  })
  
  $('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    smartSpeed:1000,
    nav:true,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
});